export const Key = {
    KeyA: ['a', 'A'],
    KeyB: ['b', 'B'],
    KeyC: ['c', 'C'],
    KeyD: ['d', 'D'],
    KeyE: ['e', 'E'],
    KeyF: ['f', 'F'],
    KeyG: ['g', 'G'],
    KeyH: ['h', 'H'],
    KeyI: ['i', 'I'],
    KeyJ: ['j', 'J'],
    KeyK: ['k', 'K'],
    KeyL: ['l', 'L'],
    KeyM: ['m', 'M'],
    KeyN: ['n', 'N'],
    KeyO: ['o', 'O'],
    KeyP: ['p', 'P'],
    KeyQ: ['q', 'Q'],
    KeyR: ['r', 'R'],
    KeyS: ['s', 'S'],
    KeyT: ['t', 'T'],
    KeyU: ['u', 'U'],
    KeyV: ['v', 'V'],
    KeyW: ['w', 'W'],
    KeyX: ['x', 'X'],
    KeyY: ['y', 'Y'],
    KeyZ: ['z', 'Z'],
    Key0: ['0'],
    Key1: ['1'],
    Key2: ['2'],
    Key3: ['3'],
    Key4: ['4'],
    Key5: ['5'],
    Key6: ['6'],
    Key7: ['7'],
    Key8: ['8'],
    Key9: ['9'],
    Left: ['ArrowLeft', 'Left'],
    Right: ['ArrowRight', 'Right'],
    Up: ['ArrowUp', 'Up'],
    Down: ['ArrowDown', 'Down'],
    Enter: ['Enter'],
    Tab: ['Tab'],
    Spacebar: [' ', 'Spacebar'],
    Alt: ['Alt'],
    Ctrl: ['Control'],
    Meta: ['Meta', 'OS'],
    Shift: ['Shift'],
};

export const ALL_KEYS = new Set([
    ...Key.KeyA,
    ...Key.KeyB,
    ...Key.KeyC,
    ...Key.KeyD,
    ...Key.KeyE,
    ...Key.KeyF,
    ...Key.KeyG,
    ...Key.KeyH,
    ...Key.KeyI,
    ...Key.KeyJ,
    ...Key.KeyK,
    ...Key.KeyL,
    ...Key.KeyM,
    ...Key.KeyN,
    ...Key.KeyO,
    ...Key.KeyP,
    ...Key.KeyQ,
    ...Key.KeyR,
    ...Key.KeyS,
    ...Key.KeyT,
    ...Key.KeyU,
    ...Key.KeyV,
    ...Key.KeyW,
    ...Key.KeyX,
    ...Key.KeyY,
    ...Key.KeyZ,
    ...Key.Key0,
    ...Key.Key1,
    ...Key.Key2,
    ...Key.Key3,
    ...Key.Key4,
    ...Key.Key5,
    ...Key.Key6,
    ...Key.Key7,
    ...Key.Key8,
    ...Key.Key9,
    ...Key.Left,
    ...Key.Right,
    ...Key.Up,
    ...Key.Down,
    ...Key.Enter,
    ...Key.Tab,
    ...Key.Spacebar,
    ...Key.Alt,
    ...Key.Ctrl,
    ...Key.Meta,
    ...Key.Shift,
]);
